# Generated by Django 4.1.2 on 2022-10-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(null=True, upload_to='img/')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ManyToManyField(null=True, to='api.photolist'),
        ),
    ]
