# Generated by Django 4.1.2 on 2022-10-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_news_category_alter_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='banner',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
