# Generated by Django 4.1.2 on 2022-10-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_photolist_remove_news_img_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='api.category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ManyToManyField(to='api.photolist'),
        ),
    ]
