# Generated by Django 4.1.2 on 2022-10-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_news_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DangChuY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.news')),
            ],
        ),
    ]
